sudo: false

notifications:
  webhooks: https://www.travisbuddy.com/

language: node_js

node_js:
  - '8'
  - '10'

before_install: if [[ `npm -v` != 6* ]]; then npm install -g npm@6; fi

install:
  - npm ci

cache:
  directories:
  - "$HOME/.npm"

after_success:
  - npm run cover:alls
